apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-config-pvc
  namespace: airsonic-advanced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # Adjust based on your StorageClass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-music-pvc
  namespace: airsonic-advanced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn  # Adjust based on your StorageClass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-playlists-pvc
  namespace: airsonic-advanced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # Adjust based on your StorageClass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-podcasts-pvc
  namespace: airsonic-advanced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # Adjust based on your StorageClass
