apiVersion: v1
kind: Service
metadata:
  name: airsonic-advanced
  namespace: airsonic-advanced
spec:
  type: NodePort
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 32015
  selector:
    app: airsonic-advanced
